version: '2.1'
services:
  typeahead:
    build: .
    environment:
      - CONSUL_HOST=${CONSUL_HOST:-notset}
      - CONSUL_PORT=${CONSUL_PORT:-8500}
    network_mode: bridge
    ports:
      - "8123:8080"
      - "8501:8500"
      - "8401:8400"