openapi: '3.0.0'


info:
  title: Typeahead
  version: '2.0.0-alpha'


paths:
  /:
    get:
      description: >-
        Search across multiple APIs.
      responses:
        200:
          description: A list of search results.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result-list'
      parameters:
      - name: q
        in: query
        description: Free-text query
        required: false
        schema:
          type: string

components:

  schemas:
    result-list:
      type: array
      items:
        type: string
